services:
  app:
    container_name: ai-internal-staging
    build: .
    env_file:
      - stack.env
    ports:
      - "3040:3005"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ai-internal-network
      - financer-transactions_transactions-network
      - staging_bff_back-end
  postgres:
    image: postgres:16-alpine
    container_name: ai-internal-staging-postgres
    env_file:
      - stack.env
    ports:
      - 5440:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:

networks:
  ai-internal-network:  
    driver: bridge
  financer-transactions_transactions-network:
    external: true
  staging_bff_back-end:
    external: true